function plotComparison(x,atws,gtws,ttws)
%
% function to plot a comparison of the three time series
%
% Input:
%   x -- the time stamps in days from 2002-01-01
%   atws -- assimilated TWS anomaly
%   gtws -- GRACE TWS anomaly
%   ttws -- EALCO TWS anomaly
%
%   no results to return
%

figure;

hold on;
plot(x,gtws,'b-o',...
    'LineWidth',1,...
    'MarkerSize',3,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5]);
plot(x,ttws,'k-*',...
    'LineWidth',1,...
    'MarkerSize',3,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor',[0.5,0.5,0.5]);
plot(x,atws,'r-s',...
    'LineWidth',2,...
    'MarkerSize',3,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor',[0.5,0.5,0.5]);
title('Comparison of the time series: ATWS(red), GTWS(blue) and ETWS(black)')
xlabel('Time in days from 2002-01-01')
ylabel('TWS Anomaly in EWH [mm]')

end

